src/DocBundle/Entity/Job.php
<?php

namespace DocBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity()
 * @ORM\Table()
 */
class Job
{
    public function __construct() {
        $this->tags = new \Doctrine\Common\Collections\ArrayCollection();
        $this->files = new \Doctrine\Common\Collections\ArrayCollection();
        $this->technos = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * function fr of the Work.
     *
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $functionFr;

    /**
     * function En of the Work.
     *
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $functionEn;

    /**
     * text fr of the Work.
     *
     * @var string
     *
     * @ORM\Column(type="text", length=65535, nullable=true)
     */
    private $textFr;

    /**
     * function En of the Work.
     *
     * @var string
     *
     * @ORM\Column(type="text", length=65535, nullable=true)
     */
    private $textEn;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateStart;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateEnd;

    /**
     * type of the execution.
     *
     * @var \tags
     *
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="jobs")
     * @ORM\JoinTable(name="tags_jobs")
     */
    private $tags;

    /**
     * @var \files
     *
     * @ORM\ManyToMany(targetEntity="File", inversedBy="jobs", cascade={"persist"})
     * @ORM\JoinTable(name="files_jobs")
     *
     */
    private $files;

    /**
     * @var ArrayCollection
     */
    private $uploadedFiles;

    /**
     * structure of the job.
     *
     * @var \structure
     *
     * @ORM\ManyToOne(targetEntity="Structure", inversedBy="jobs")
     * @ORM\JoinColumn(name="job_structure", referencedColumnName="id")
     */
    private $structure;

    /**
     * technos of the job
     *
     * @var \technos
     *
     * @ORM\ManyToMany(targetEntity="Techno", inversedBy="jobs")
     * @ORM\JoinTable(name="techno_jobs")
     */
    private $technos;

















    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set functionFr.
     *
     * @param string $functionFr
     *
     * @return Work
     */
    public function setFunctionFr($functionFr)
    {
        $this->functionFr = $functionFr;

        return $this;
    }

    /**
     * Get functionFr.
     *
     * @return string
     */
    public function getFunctionFr()
    {
        return $this->functionFr;
    }

    /**
     * Set functionEn.
     *
     * @param string $functionEn
     *
     * @return Work
     */
    public function setFunctionEn($functionEn)
    {
        $this->functionEn = $functionEn;

        return $this;
    }

    /**
     * Get functionEn.
     *
     * @return string
     */
    public function getFunctionEn()
    {
        return $this->functionEn;
    }

    /**
     * Set textFr.
     *
     * @param string $textFr
     *
     * @return Work
     */
    public function setTextFr($textFr)
    {
        $this->textFr = $textFr;

        return $this;
    }

    /**
     * Get textFr.
     *
     * @return string
     */
    public function getTextFr()
    {
        return $this->textFr;
    }

    /**
     * Set textEn.
     *
     * @param string $textEn
     *
     * @return Work
     */
    public function setTextEn($textEn)
    {
        $this->textEn = $textEn;

        return $this;
    }

    /**
     * Get textEn.
     *
     * @return string
     */
    public function getTextEn()
    {
        return $this->textEn;
    }

    /**
     * Set dateStart.
     *
     * @param \DateTime $dateStart
     *
     * @return Work
     */
    public function setDateStart($dateStart)
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    /**
     * Get dateStart.
     *
     * @return \DateTime
     */
    public function getDateStart()
    {
        return $this->dateStart;
    }

    /**
     * Set dateEnd.
     *
     * @param \DateTime $dateEnd
     *
     * @return Work
     */
    public function setDateEnd($dateEnd)
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    /**
     * Get dateEnd.
     *
     * @return \DateTime
     */
    public function getDateEnd()
    {
        return $this->dateEnd;
    }

    /**
     * Set tag.
     *
     * @param $tags
     *
     * @return work
     */
    public function setTags($tags)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Get tags.
     *
     * @return tags
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * set files.
     *
     * @return work
     */
    public function setFiles($files)
    {
        $this->files = $files;

        return $this;
    }

    /**
     * get files.
     *
     * @return files
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * set uploadedFiles.
     *
     * @return work
     */
    public function setUploadedFiles($uploadedFiles)
    {
        $this->uploadedFiles = $uploadedFiles;

        return $this;
    }

    /**
     * get uploadedFiles.
     *
     * @return uploadedFiles
     */
    public function getUploadedFiles()
    {
        return $this->uploadedFiles;
    }

    /**
     * Set structure.
     *
     * @param $structure
     *
     * @return Job
     */
    public function setStructure($structure)
    {
        $this->structure = $structure;

        return $this;
    }

    /**
     * Get structure.
     *
     * @return structure
     */
    public function getStructure()
    {
        return $this->structure;
    }

    /**
     * Set technos.
     *
     * @param $technos
     *
     * @return work
     */
    public function setTechnos($technos)
    {
        $this->technos = $technos;

        return $this;
    }

    /**
     * Get technos.
     *
     * @return technos
     */
    public function getTechnos()
    {
        return $this->technos;
    }


    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return explode("@", $this->functionFr)[0];
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getNameProject()
    {
        return explode("@", $this->functionFr)[1];
    }
}

src/DocBundle/Form/JobType.php
<?php

namespace DocBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class JobType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('functionFr',     'text')
            ->add('functionEn',     'text', array(
                                    'required' => false))
            ->add('textFr',         'textarea', array(
                                    'attr' => array('rows' => '10'),
                                    'required' => false))
            ->add('textEn',         'textarea', array(
                                    'attr' => array('rows' => '10'),
                                    'required' => false))
            ->add('dateStart',      'date', array(
                                    'widget' => 'single_text',
                                    'input' => 'datetime',
                                    'format' => 'dd/MM/yyyy',
                                    'required' => false))
            ->add('dateEnd',        'date', array(
                                    'widget' => 'single_text',
                                    'input' => 'datetime',
                                    'format' => 'dd/MM/yyyy',
                                    'required' => false))
            ->add('structure',      'entity', array(
                                    'class' => 'DocBundle:Structure',
                                    'choice_label' => 'name',
                                    'required' => false))
            ->add('technos',        'entity', array(
                                    'class' => 'DocBundle:Techno',
                                    'choice_label' => 'name',
                                    'multiple' => true,
                                    'expanded' => true))
            ->add('tags',           'entity', array(
                                    'class' => 'DocBundle:Tag',
                                    'choice_label' => 'nameFr',
                                    'multiple' => true,
                                    'expanded' => true))
            ->add('uploadedFiles',  'file', array(
                                    'label' => 'Ajouter des uploadedFiles',
                                    'required' => false,
                                    'multiple' => true,
                                    'data_class' => null))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'DocBundle\Entity\Job'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'docbundle_job';
    }
}

src/DocBundle/Controller/JobController.php
<?php

namespace DocBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use DocBundle\Entity\Job;
use DocBundle\Form\JobType;
use DocBundle\Entity\File;
use Doctrine\ORM\EntityManager;

/**
 * Job controller.
 *
 */
class JobController extends Controller
{
    /**
     * Lists all Job entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('DocBundle:Job')->findBy([], array('dateStart' => 'desc'));

        dump($entities);

        $_SESSION['jobIdsDetailNavigation'] = $this->get('doc.navigation')->getOnlyIds($entities);

        $isAdmin = $this->get('doc.utils')->isAdmin($this->container->get('request'));

        return $this->render('DocBundle:Job:index.html.twig', array(
            'entities' => $entities,
            "isAdmin" => $isAdmin
        ));
    }


    /**
     * Creates a new Job entity.
     *
     */
    public function newAction(Request $request)
    {
        $entity = new Job();

        $form = $this->createForm(new JobType(), $entity);

        $form->add('submit', 'submit', array('label' => 'Create'));

        $form->handleRequest($request);

        if ($form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            $this->get('doc.file')->saveUploadedFiles($entity, 'job', $entity->getfunctionFr());

            return $this->redirect($this->generateUrl('job_show', array('id' => $entity->getId())));
        }

        return $this->render('DocBundle:Job:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }


    /**
     * Displays a form to edit an existing Job entity.
     *
     */
    public function editAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('DocBundle:Job')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $form = $this->createForm(new JobType(), $entity);
        $form->add('submit', 'submit', array('label' => 'Update'));

        if ($form->handleRequest($request)->isValid()) {

            $em->persist($entity);
            $em->flush();

            //$nameStructure = $entity->getStructure() !== null ? $entity->getStructure()->getName() : "";

            $this->get('doc.file')->saveUploadedFiles($entity, 'job', $entity->getfunctionFr());

            dump($entity);

            return $this->redirect($this->generateUrl('job_show', array('id' => $entity->getId())));
        }

        return $this->render('DocBundle:Job:new.html.twig', array(
            'entity'  => $entity,
            'form'    => $form->createView()
        ));
    }


    /**
     * Finds and displays a Job entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('DocBundle:Job')->find($id);

        dump($entity);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $ids = isset($_SESSION['jobIdsDetailNavigation'])
              ? $_SESSION['jobIdsDetailNavigation']
              : $this->get('doc.navigation')->getOnlyIds($em->getRepository('DocBundle:Job')->findAll());

        $works = $em->getRepository('DocBundle:Work')->findBy(["job" => $entity], array('dateStart' => 'desc'));

        return $this->render('DocBundle:Job:show.html.twig', array(
            'entity' => $entity,
            'ids' => $ids,
            'works' => $works
        ));
    }


    /**
     * Deletes a Job entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('DocBundle:Job')->find($id);

        if ($entity) {
          $this->get('doc.file')->removeFiles($entity->getFiles());
          $em->remove($entity);
          $em->flush();
        }

        return $this->redirectToRoute('job');
    }
}

src/DocBundle/Resources/views/Job/index.html.twig
{% extends '::base.html.twig' %}

{% block title %}Job{% endblock %}

{% block body -%}

    <h1>Job list</h1>

    {% if isAdmin %}

            <a href="{{ path('job') }}" class="btn btn-default">Mode public</a>

            <a href="{{ path('job_new') }}" class="btn btn-default">Créer un nouvel élément</a>

            <br><br>

            <div class="row firstLineTable">

                <strong>

                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-md-2">
                                id
                            </div>
                            <div class="col-md-10">
                                <strong>Fonction</strong>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-2">
                        Texte
                    </div>

                    <div class="col-md-1">
                        Date début / fin
                    </div>

                    <div class="col-md-1">
                        structure
                    </div>

                    <div class="col-md-1">
                        Techno
                    </div>

                    <div class="col-md-1">
                        Tags
                    </div>

                    <div class="col-md-1">
                        Images
                    </div>

                    <div class="col-md-1">
                        Actions
                    </div>

                </strong>

            </div>

            <br>

            {% for entity in entities %}

                <div class="row {% if loop.index is even %}rowBgEven{% else %}rowBgOdd{% endif %}">

                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-md-2">
                                {{ entity.id }}
                            </div>
                            <div class="col-md-10">
                                <strong>{{ entity.functionFr }}</strong>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-2" title="{{ entity.textFr }}">
                        {{ entity.textFr|truncate(50) }}
                    </div>

                    <div class="col-md-1">
                        {% if entity.dateStart %}{{ entity.dateStart|date('Y') }}{% endif %}
                        {% if entity.dateEnd %} à {{ entity.dateEnd|date('Y') }}{% endif %}
                    </div>

                    <div class="col-md-1">
                        {% if entity.structure %}
                            {{ entity.structure.name }}
                        {% endif %}
                    </div>

                    <div class="col-md-1">
                        {% if entity.technos|length > 0 %}
                            <a title="{{ UtilsService.getConcatenateTechnos(entity.technos) }}">{{ entity.technos|length }} items</a>
                        {% endif %}
                    </div>

                    <div class="col-md-1">
                        {% if entity.tags|length > 0 %}
                            <a title="{{ UtilsService.getConcatenateTags(entity.tags) }}">{{ entity.tags|length }} items</a>
                        {% endif %}
                    </div>

                    <div class="col-md-1">
                        {% set nbFiles = entity.files|length %}
                        {% if nbFiles > 0 %}
                            <div class="vignetteListe" style="background-image:url({{ asset('files/' ~ entity.files[0].fileName ) }})">
                                <div class="pastilleVignette">
                                    {{ nbFiles }}
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <div class="col-md-1">
                        <div class="row">
                            <a class="col-md-12" href="{{ path('job_show', { 'id': entity.id }) }}">Consulter</a>
                            <a class="col-md-12" href="{{ path('job_edit', { 'id': entity.id }) }}">Modifier</a>
                            <a class="col-md-12" href="{{ path('job_delete', { 'id': entity.id }) }}" onclick="return confirm('are u sure?')">Supprimer</a>
                        </div>
                    </div>

                </div>

            {% endfor %}

        {% else %}










            <a href="{{ path('job_admin') }}" class="btn btn-default">Mode admin</a>

            <br><br>

            <div class="row jobRowList">

                {% for entity in entities %}

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 sizeRowList">

                        <div class="borderRowList">

                            <a class="mainLinkRowList" href="{{ path('job_show', { 'id': entity.id })}}">
                                <img src=" {{ asset('files/' ~ entity.files[0].fileName ) }}" class="img-responsive center-block vertical-center" />
                            </a>

                            <div class="blockList">

                                <div class="blockInfoList jobList">

                                      <div class="listeDate">

                                          {% if entity.dateStart %}
                                              {{ entity.dateStart|date('Y') }}
                                          {% endif %}
                                              à
                                          {% if entity.dateEnd %}
                                              {{ entity.dateEnd|date('Y') }}
                                          {% else %}
                                              aujourd'hui
                                          {% endif %}

                                      </div>

                                      <div class="listeTitre">

                                          {{ entity.name }}

                                          {#
                                              cas particulier
                                              id 6 -> Open
                                              id 1 -> auto entreprise
                                              #}

                                          {% if entity.structure.id == 6 or entity.structure.id == 1 %}

                                           @ {{ entity.nameProject|upper }}

                                          {% endif %}

                                      </div>

                                      <div class="listeJobStructure blue">

                                           <a href="{{ path('structure_show', { 'id': entity.structure.id }) }}">{{ entity.structure.name|upper }}</a> ({{ entity.structure.city }})

                                      </div>


                                </div>

                                {% if entity.technos|length > 0 %}

                                <div class="encadreJobsMissionProjet">

                                    {% for entity in entity.technos|sortByField("startedYear") %}
                                        <a href="{{ path('techno_show', { 'id': entity.id }) }}" style="text-decoration:none;">
                                            <img src=" {{ asset('files/' ~ entity.files[0].fileName ) }}" class="miniLogoEnLigne50" title="{{ entity.name }} ({{ entity.technoCategory.nameFr }})" />
                                        </a>
                                    {% endfor %}

                                </div>

                                {% endif %}

                            </div>

                        </div>

                    </div>

                {% endfor %}

            </div>

        {% endif %}


{% endblock %}

src/DocBundle/Resources/views/Job/new.html.twig
{% extends '::base.html.twig' %}

{% block title %}New Job{% endblock %}

{% block stylesheets %}


{% endblock %}



{% block body -%}

    <h3>Création d'un job</h3>

	<div class="well">

	  	{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}


		    {{ form_errors(form) }}


		    <div class="form-group">

			      {{ form_label(form.functionFr, "functionFr", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

			      {{ form_errors(form.functionFr) }}

			      <div class="col-sm-4">
			        {{ form_widget(form.functionFr, {'attr': {'class': 'form-control'}}) }}
			      </div>

		    </div>


			<div class="form-group">

		      {{ form_label(form.functionEn, "functionEn", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.functionEn) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.functionEn, {'attr': {'class': 'form-control'}}) }}
		      </div>

		    </div>


		    <div class="form-group">

		      {{ form_label(form.textFr, "textFr", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.textFr) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.textFr, {'attr': {'class': 'form-control'}}) }}
		      </div>

		    </div>



		    <div class="form-group">

		      {{ form_label(form.textEn, "textEn", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.textEn) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.textEn, {'attr': {'class': 'form-control'}}) }}
		      </div>

		    </div>


		    <div class="form-group">

		      {{ form_label(form.dateStart, "dateStart", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.dateStart) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.dateStart, {'attr': {'class': 'form-control'}}) }}
		      </div>

		    </div>



		    <div class="form-group">

		      {{ form_label(form.dateEnd, "dateEnd", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.dateEnd) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.dateEnd, {'attr': {'class': 'form-control'}}) }}
		      </div>

		    </div>


		    <div class="form-group">

		      {{ form_label(form.structure, "structure", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.structure) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.structure, {'attr': {'class': 'form-control'}}) }}
		      </div>

		    </div>



		    <div class="form-group">

		      {{ form_label(form.technos, "technos", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.technos) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.technos, {'attr': {'class': 'technos'}}) }}
		      </div>

		    </div>



		    <div class="form-group">

		      {{ form_label(form.tags, "tags", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.tags) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.tags, {'attr': {'class': 'tags'}}) }}
		      </div>

		    </div>



		    <div class="form-group">

		      {{ form_label(form.uploadedFiles, "uploadedFiles", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

		      {{ form_errors(form.uploadedFiles) }}

		      <div id="block_image" class="col-sm-4">

			      	{% for file in entity.files %}
	                	<a class="delete_file" id="file_{{ file.id }}" href="javascript: file_delete({{ file.id }})" onclick="return confirm('are u sure?')">
	                		<img src=" {{ asset('assets/close.png') }}" class="close_cross" />
	                		<img src=" {{ asset('files/' ~ file.fileName ) }}" class="image absoluteIndex" />
	                	</a>
	            	{% endfor %}	

	            	<div class="row">
	            		<div class="col-sm-12">
			            	<label class="myLabel">
		    					<input type="file" id="docbundle_job_uploadedFiles" name="docbundle_job[uploadedFiles][]" multiple="multiple" class="form-control">
		    					<span>Ajouter des fichiers</span>
							</label>
						</div>
					</div>

            	</div>

		    </div>


			<div class="row">

				<div class="col-sm-3">
					<a href="{{ path('job') }}">
            			Back to the list
        			</a>
		    	</div>

				<div class="col-sm-4">
		    		{{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary'}}) }}
		    	</div>

		    </div>


		{{ form_row(form._token) }}

		{{ form_end(form, {'render_rest': false}) }}


	</div>


{% endblock %}



{% block javascripts %}

	<script>

	$( function() {
        $("#docbundle_job_dateStart").datepicker($.datepicker.regional['fr']);
        $("#docbundle_job_dateEnd").datepicker($.datepicker.regional['fr']);
        });

        

            //alert("toto");
        </script>
	
{% endblock %}

src/DocBundle/Resources/views/Job/show.html.twig
{% extends '::base.html.twig' %}

{% block title %}Job{% endblock %}

{% block body -%}

    <h1>{{ entity.functionFr }}</h1>


    <div class="row">

        <div class="col-sm-6">

            {{ include("DocBundle:Common:caroussel.html.twig") }}

        </div>


        <div class="col-sm-6 blockItemDetail">

            <div>Date : <strong> De {{ entity.dateStart|date('F Y') }} à {{ entity.dateEnd|date('F Y') }}</strong></div>

            <div>Description : <strong>{{ entity.textFr|nl2br }}</strong></div>

            {% if entity.tags|length > 0 %}

                <div>Tags :<strong> {{ UtilsService.getConcatenateTagsInLine(entity.tags, ", ") }}</strong></div>

            {% endif %}

            <div>Technologies mises en oeuvre :</div>

            <div class="technosListeItemDetail">

                {% for entity in entity.technos|sortByField("startedYear") %}
                    <a href="{{ path('techno_show', { 'id': entity.id }) }}">
                        <img src=" {{ asset('files/' ~ entity.files[0].fileName ) }}" class="miniLogoEnLigne50" title="{{ entity.name }} ({{ entity.technoCategory.nameFr }})" />
                    </a>
                {% endfor %}

            </div>

        </div>

    </div>




    <div class="adminDetail">
      <ul class="record_actions">
          <li>
              <a href="{{ path('job') }}">
                  Back to the list
              </a>
          </li>
          <li>
              <a href="{{ path('job_edit', { 'id': entity.id }) }}">
                  Edit
              </a>
          </li>
          <li>
              <a href="{{ path('job_delete', { 'id': entity.id }) }}" onclick="return confirm('are u sure?')">Supprimer</a>
          </li>
      </ul>
    <div>







    <div class="row workRowList">

        {% if works|length > 0 %}
            <div class="titleAssociatedWorks">Travaux associés</div>
        {% endif %}

        {% for entity in works %}

            <div class="col-xs-3 col-sm-3 col-md-3" style="height:300px;">

                {% if entity.files|length > 0 %}
                    <a class="mainLinkRowList" href="{{ path('work_show', { 'id': entity.id })}}">
                        <img src=" {{ asset('files/' ~ entity.files[0].fileName ) }}" class="img-responsive center-block vertical-center" />
                    </a>
                {% endif %}

                <div class="blockInfoList">

                    <div class="listeDate blue">

                        {{ entity.workType.nameFr }}

                        (
                        {% if entity.dateStart %}
                            {{ entity.dateStart|date('F Y') }}
                        {% endif %}
                        )

                    </div>

                    <div class="listeTitre">

                        {{ entity.nameFr }}

                    </div>

                </div>

            </div>

        {% endfor %}

    </div>

{% endblock %}